### ISSUE TITLE
gvim support

### ISSUE THREAD

**Issue by mgraham** [wellle/tmux-complete.vim#58]
I use gvim in one window and tmux in another.  In this configuration, tmuxcomplete silently fails.

After some digging, I discovered that the tmuxcomplete shell script is complaining that it is not being run from within tmux. 

```
if [ -z "$TMUX_PANE" ]; then
    echo "Not running inside tmux!" 1>&2
    exit 1
fi
```

However, it turns out that it is not necessary to run within tmux in order to interact with a running tmux.  If I remove that check from the tmuxcomplete shell script, then the script works fine.

**Comment by wellle** [comment]
Oh that's awesome!

Did you check what happens without that check if no tmux is running at all?

We might want to use a different (less restrictive) check to see if any tmux is running anywhere.

Thanks for the heads up :+1:
