### ISSUE TITLE
Integrate w/ deoplete?

### ISSUE THREAD

**Issue by cirqueit** [wellle/tmux-complete.vim#67]
I was wondering if you knew how to use tmux-complete w/ deoplete

I tried `omnifunc=tmuxcomplete#completions`

**Comment by alexbooker** [comment]
I would also like to know this. Thank you.

**Comment by wellle** [comment]
Oh, thanks for reminding me. This issue must have slipped through the cracks.

I will try to look into it soon :+1:

**Comment by wellle** [comment]
@cirqueit @alexbooker: I added a basic completion source in branch [`67-deoplete`](https://github.com/wellle/tmux-complete.vim/compare/67-deoplete). Can you try that and let me know if that works for you? Thanks!

**Comment by cirqueit** [comment]
@wellle Working great. Thanks a lot!

**Comment by alexbooker** [comment]
@wellle Only tested it briefly but it certainly seems to work:

![](http://i.imgur.com/JXRBx8F.png)

**Comment by wellle** [comment]
Thanks guys. Will merge soon.

**Comment by alexbooker** [comment]
@wellle Thank _you_ for jumping on this so quickly :open_mouth:

**Comment by wellle** [comment]
Merged in #70 and released as [`v0.1.2`](https://github.com/wellle/tmux-complete.vim/releases/tag/v0.1.2).

**Comment by alexbooker** [comment]
Been enjoying the `deoplete` branch all day. You're the man!
