### ISSUE TITLE
Complete from all windows and all panes?

### ISSUE THREAD

**Issue by kdheepak** [wellle/tmux-complete.vim#75]
Do you know if this will be possible / do you think there is interest in implementing this feature? Currently, it appears it only completes from adjacent panes, is that correct? Perhaps a feature where it completes from all panes and all windows could be added as an optional feature.

**Comment by wellle** [comment]
@kdheepak: It's already capable of doing that. I just tested again and was able to complete a words from a different window and a different session. I was using the plugin on its own and triggered it with the default <kbd>C-X</kbd><kbd>X-U</kbd> combo.

Could it be that you're using a completion plugin integration? If so, which one?

**Comment by kdheepak** [comment]
I see. It's possible that it's because of that. I'm using deocomplete

**Comment by wellle** [comment]
Hmm, I tried it with deoplete. I'm using this setup:
```vim
Plug '~/code/tmux-complete.vim' " local version version for development, up to date with origin/master
Plug 'Shougo/deoplete.nvim'
let g:deoplete#enable_at_startup = 1
```

And it works for me. I'm using Vim in a tmux pane next to one where I typed `aaaccc`. In a different window I'm having `aaaddd`. And in another session `aaabbb`. When I type `aaa` in Vim I'm getting all three suggestions.

Can you try the same setup?

**Comment by kdheepak** [comment]
Thanks for looking into this in so much detail. I'm able to replicate this example fine. It could be an issue with another plugin (would have even affect this?). Or perhaps it's a long running session / lots of text that causes this. I'll see if I can isolate the issue and post a more minimal working example the next time I encounter this. I will close this now. Thanks again for the quick responses!
