### ISSUE TITLE
deoplete source: use async functionality

### ISSUE THREAD

**Issue by blueyed** [wellle/tmux-complete.vim#80]
deoplete has async support for sources by now, which could be used probably with the async work that has been done here lately.

Haven't investigated, but wanted to open this for ideas/discussion already.

**Comment by balta2ar** [comment]
After deoplete moved to multiprocessing ("one source -- one process") model this spring, I don't see many reasons to write `async` plugins (in deoplete terms) anymore. You can just block whatever you want and neither editor nor deoplete core will be blocked because of that.

**Comment by blueyed** [comment]
Yep, closing.

I've thought about using asyncio with deoplete, but that would still allow sources to block, of course.
