### ISSUE TITLE
Trigger setting for coc?

### ISSUE THREAD

**Issue by lovesegfault** [wellle/tmux-complete.vim#85]
What is the appropriate trigger setting for coc integration?

**Comment by wellle** [comment]
@kabouzeid: Can you help here?

**Comment by kabouzeid** [comment]
I don’t quite understand. Everything should work right out of the box.

**Comment by hovnatan** [comment]
@kabouzeid I can't get coc.nvim complete work with tmux-complete. My configs are https://github.com/hovnatan/dotfiles/blob/master/.config/nvim/init.vim. Can you please help?

**Comment by kabouzeid** [comment]
Have you run :PlugUpdate ?

**Comment by hovnatan** [comment]
`:PlugUpdate` did the trick! Thanks and sorry :)
